name: Terraform apply destroy

on:
  workflow_dispatch:
    inputs:
      command:
        
        type: choice
        description: delect command
        options:
        - apply
        - destroy
        
  # push:
  #   branches:
  #     - main

jobs:
  create:
    runs-on: ubuntu-latest
    
    env:
      
      AWS_REGION: ap-south-1
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan   
      - name: Deploying the infrastructure
       
        run: |
          terraform ${{ inputs.command }} --auto-approve
