name: Terraform destroy
on:
  workflow_dispatch:
    # inputs:
    #   region:
    #     description: 'Region'
    #     required: true


jobs:
  create:
    runs-on: ubuntu-latest
    env:
        working-directory: ./
        

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id :  ${{ secrets.ACCESS_KEY}}
          aws-secret-access-key : ${{ secrets.SECRET_ACCESS_KEY }}
          aws-session-token :     ${{ secrets.SESSION_TOKEN }}
          aws-region: ${{ inputs.region }}
  
      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v2

      # - name: Apply New Relic deployment marker
      #   uses: newrelic/deployment-marker-action@v0.1.1
      #   with:
      #     apiKey: ${{ secrets.NEW_RELIC_API_KEY }}  
      #     region: US                                    
      #     accountId:          
      #     user: ${{ secrets.account_id }}   

      - name: Deploying the infrastructure
        working-directory: ${{env.working-directory}}
        run: |
          terraform init
          terraform plan
          terraform destroy --auto-approve
